Fix fuer #477.

diff --git a/sbin/linuxmuster-migration-restore b/sbin/linuxmuster-migration-restore
--- a/sbin/linuxmuster-migration-restore
+++ b/sbin/linuxmuster-migration-restore
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # thomas@linuxmuster.net
-# 04.07.2014
+# 06.10.2015
 # GPL v3
 #
 
@@ -66,16 +66,18 @@ fi
 # delete old logfile
 rm -f "$MIGRESTLOG"
 
+# logging
+exec >>$MIGRESTLOG 2>&1
 
 # print script header info
 echo
-echo "####" | tee -a "$MIGRESTLOG"
-echo "#### Starting restore of migration data" | tee -a "$MIGRESTLOG"
-echo "#### Sourcedir: $SOURCEDIR" | tee -a "$MIGRESTLOG"
-echo "#### Configdir: $MIGCONFDIR" | tee -a "$MIGRESTLOG"
-[ -n "$NFSTMPDIR" ] && echo "#### NFS-Tempdir: $NFSTMPDIR" | tee -a "$MIGRESTLOG"
-echo "#### `date`" | tee -a "$MIGRESTLOG"
-echo "####" | tee -a "$MIGRESTLOG"
+echo "####"
+echo "#### Starting restore of migration data"
+echo "#### Sourcedir: $SOURCEDIR"
+echo "#### Configdir: $MIGCONFDIR"
+[ -n "$NFSTMPDIR" ] && echo "#### NFS-Tempdir: $NFSTMPDIR"
+echo "#### `date`"
+echo "####"
 
 # nfs check
 RET="$(nfs_check)"
@@ -85,12 +87,12 @@ if [ -n "$RET" ]; then
  NFSTYPE="$(echo "$RET" | awk '{ print $3 }')"
 
  if [ -n "$NFSSHARE" -a -n "$NFSMNTDIR" -a -n "$NFSTYPE" ]; then
-  echo "$NFSTYPE filesystem $NFSSHARE is mounted on $NFSMNTDIR." | tee -a "$MIGRESTLOG"
+  echo "$NFSTYPE filesystem $NFSSHARE is mounted on $NFSMNTDIR."
  else
-  echo "NFSSHARE:  $NFSSHARE" | tee -a "$MIGRESTLOG"
-  echo "NFSMNTDIR: $NFSMNTDIR" | tee -a "$MIGRESTLOG"
-  echo "NFSTYPE:   $NFSTYPE" | tee -a "$MIGRESTLOG"
-  error "NFS error!" | tee -a "$MIGRESTLOG"
+  echo "NFSSHARE:  $NFSSHARE"
+  echo "NFSMNTDIR: $NFSMNTDIR"
+  echo "NFSTYPE:   $NFSTYPE"
+  error "NFS error!"
  fi
 fi
 
@@ -116,18 +118,18 @@ if [ -n "$NFSTYPE" ]; then
  done
 
  if [ -z "$LOCALSRCDIR" ]; then
-  error "There is not enough free space on the local filesystem! About $(( $ssum / 1024 )) MB are needed." | tee -a "$MIGRESTLOG"
+  error "There is not enough free space on the local filesystem! About $(( $ssum / 1024 )) MB are needed."
  fi
 
- mkdir -p "$LOCALSRCDIR" | tee -a "$MIGRESTLOG"
- echo -n "Copying about $(( $ssum / 1024 )) MB data to $LOCALSRCDIR ... be patient ..." | tee -a "$MIGRESTLOG"
+ mkdir -p "$LOCALSRCDIR"
+ echo -n "Copying about $(( $ssum / 1024 )) MB data to $LOCALSRCDIR ... be patient ..."
  RC=0
- rsync -a -v --delete "$SOURCEDIR/" "$LOCALSRCDIR/" 2>> "$MIGRESTLOG" 1>> "$MIGRESTLOG" || RC=1
+ rsync -a -v --delete "$SOURCEDIR/" "$LOCALSRCDIR/" || RC=1
  if [ "$RC" = "0" ]; then
-  echo " OK!" | tee -a "$MIGRESTLOG"
+  echo " OK!"
  else
   rm -rf "$LOCALSRCDIR"
-  error " Failed!" | tee -a "$MIGRESTLOG"
+  error " Failed!"
  fi
 
  SOURCEDIR="$LOCALSRCDIR"
@@ -148,28 +150,28 @@ cd "$SOURCEDIR"
 # concenate config files
 MIGEXUSER="$MIGCONFDIR/exclude.conf"
 MIGINUSER="$MIGCONFDIR/include.conf"
-concenate_configs || error " Failed!" | tee -a "$MIGRESTLOG"
+concenate_configs || error " Failed!"
 [ -n "$NFSTYPE" ] && echo "$SOURCEDIR" >> "$EXCONFTMP"
 
 
 # check for custom.conf and read it
 if [ -s "$MIGCONFDIR/custom.conf" ]; then
- echo -n "Reading $MIGCONFDIR/custom.conf ..." | tee -a "$MIGRESTLOG"
+ echo -n "Reading $MIGCONFDIR/custom.conf ..."
  if . "$MIGCONFDIR/custom.conf"; then
-  echo " OK!" | tee -a "$MIGRESTLOG"
+  echo " OK!"
  else
-  error " Failed!" | tee -a "$MIGRESTLOG"
+  error " Failed!"
  fi
 fi
 
 
 # keep old internsubrange, we need it later if it has to be changed during migration
 internsubrange_old="$(echo get linuxmuster-base/internsubrange | debconf-communicate | awk '{ print $2 }')"
-[ -z "$internsubrange_old" ] && error "Cannot get internsubrange value from debconf!" | tee -a "$MIGRESTLOG"
+[ -z "$internsubrange_old" ] && error "Cannot get internsubrange value from debconf!"
 
 
 # source restore script
-. "$MIGDATADIR/linuxmuster-migration-restore.sh" 2>&1 | tee -a "$MIGRESTLOG"
+. "$MIGDATADIR/linuxmuster-migration-restore.sh" 2>&1
 cp "$MIGRESTLOG" "$SOURCEDIR"
 
 
